model_opts:
  name: "FPN"
  args:
    encoder_name: "vgg19"
    encoder_weights: "imagenet"
    in_channels: 15
    classes: 3
    encoder_depth: 5
    decoder_dropout: 0.3
    activation: "softmax2d"
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
metrics_opts:
  IoU:
    threshold: 0.4
  pixel_acc:
    threshold: 0.4
  precision:
    threshold: 0.4
  recall:
    threshold: 0.4
  dice:
    threshold: 0.4
log_opts:
  mask_names: ["Clean Ice", "Debris", "Background"]
  reg_opts:
    l1_reg: 0.0005
